TRIGGER_TIMEFRAMES = ("M3", "M5", "M15")
MAX_TRIGGER_AGE = {"M3": 6, "M5": 5, "M15": 4}
TIMEFRAME_PRIORITY = {"M5": 3, "M3": 2, "M15": 1}

MIN_SCORE = 8.0
MIN_RR = 2.5
SETUP_NAME = "HTF Structure + Sweep/MSS/iFVG"

LTF_SWEEP_SCAN_BARS = 36
LTF_SWEEP_START_INDEX = 10
LTF_SWEEP_LOOKBACK_LOWS = 8
LTF_SWEEP_LOOKBACK_HIGHS = 12
LTF_SWEEP_MIN_DEPTH_RANGE_RATIO = 0.08
LTF_SWEEP_MIN_DEPTH_POINTS = 4

LTF_MSS_LOOKAHEAD_BARS = 8
LTF_MSS_MIN_BREAK_RANGE_RATIO = 0.08
LTF_MSS_MIN_BREAK_POINTS = 4
LTF_MSS_QUALITY_BASE = 0.56
LTF_MSS_QUALITY_BREAK_SCALE = 0.2
LTF_MSS_QUALITY_BODY_SCALE = 0.24

LTF_IFVG_SEARCH_BACK = 18
LTF_IFVG_POST_BREAK_BARS = 4
LTF_IFVG_STRICT_BASE_QUALITY = 0.78
LTF_IFVG_INTERNAL_BASE_QUALITY = 0.62
LTF_IFVG_WIDTH_QUALITY_SCALE = 0.12
LTF_IFVG_STRICT_ENTRY_WEIGHT = 0.1
LTF_IFVG_INTERNAL_ENTRY_WEIGHT = 0.16
LTF_IFVG_ENTRY_DISTANCE_WIDTH_RATIO = 2.0
LTF_IFVG_ENTRY_DISTANCE_RANGE_RATIO = 0.35
LTF_IFVG_ENTRY_DISTANCE_MIN_POINTS = 8
LTF_IFVG_ENTRY_MIN_QUALITY = 0.6
LTF_IFVG_INTERNAL_MIN_ENTRY_QUALITY = 0.45
LTF_IFVG_MIN_WIDTH_RATIO = 0.05
LTF_IFVG_MIN_POINTS = 4
LTF_IFVG_ARM_MIN_WIDTH_RATIO = 0.08
LTF_IFVG_ARM_MIN_QUALITY = 0.82
LTF_IFVG_ARM_MIN_ORIGIN_BODY = 0.58
LTF_IFVG_ARM_MIN_WIDTH_TO_SPAN_RATIO = 0.18
LTF_IFVG_ARM_CONTEXT_BARS = 6

LTF_SWEEP_QUALITY_BASE = 0.48
LTF_SWEEP_QUALITY_DEPTH_SCALE = 0.2
LTF_SWEEP_QUALITY_WICK_SCALE = 0.18
LTF_SWEEP_QUALITY_RECLAIM_BONUS = 0.14
LTF_POST_SWEEP_DISPLACEMENT_MIN_BARS = 2
LTF_POST_SWEEP_DISPLACEMENT_MIN_STRONG_BARS = 1
LTF_POST_SWEEP_DISPLACEMENT_MIN_BODY = 0.58
LTF_POST_SWEEP_DISPLACEMENT_MIN_MOVE_RATIO = 0.7
LTF_POST_SWEEP_DISPLACEMENT_MIN_DIRECTIONAL_RATIO = 0.67
LTF_POST_SWEEP_DISPLACEMENT_MAX_OPPOSITE_BARS = 1
LTF_COUNTERTREND_SWEEP_MIN_QUALITY = 0.78
LTF_COUNTERTREND_IFVG_MIN_QUALITY = 0.9
LTF_COUNTERTREND_DISPLACEMENT_MIN_QUALITY = 0.78
LTF_RECLAIM_MIN_DISTANCE_RATIO = 0.12
LTF_RECLAIM_MIN_QUALITY = 0.72
LTF_RECLAIM_STRONG_QUALITY = 0.84
LTF_RECLAIM_HOLD_BARS = 2
LTF_ALIGNED_SWEEP_RECLAIM_MIN_QUALITY = 0.84
LTF_ALIGNED_SWEEP_DISPLACEMENT_MIN_QUALITY = 0.84
LTF_ALIGNED_SWEEP_IFVG_MIN_QUALITY = 0.88

LTF_STOP_BUFFER_POINTS = 6
LTF_STOP_BUFFER_RANGE_RATIO = 0.08
LTF_MIN_RISK_POINTS = 5
LTF_STOP_VALIDITY_MAX_RANGE = 3.5

LTF_ACTIONABLE_ZONE_HEIGHT_RATIO = 0.75
LTF_ACTIONABLE_RISK_RATIO = 0.22
LTF_ACTIONABLE_MIN_POINTS = 10
LTF_NO_CHASE_MIN_SCORE = 0.6
LTF_NO_CHASE_RISK_RATIO = 0.55
LTF_NO_CHASE_MIN_POINTS = 10

LTF_ENTRY_LOCATION_IFVG_WEIGHT = 0.55
LTF_ENTRY_LOCATION_MODE_WEIGHT = 0.45
LTF_ENTRY_LOCATION_STRICT_SCORE = 1.0
LTF_ENTRY_LOCATION_INTERNAL_SCORE = 0.72

SIGNAL_EXPIRY_MINUTES = {"M3": 20, "M5": 30, "M15": 60}
SIGNAL_AMBIGUITY_DELTA = 0.4

# Watch mode arms on HTF + external sweep + strict iFVG,
# then waits a limited number of closed bars for a meaningful MSS trigger.
WATCH_EXPIRY_BARS = {"M3": 8, "M5": 6, "M15": 5}
WATCH_INVALIDATION_BUFFER_POINTS = 2
