from __future__ import annotations

from copy import deepcopy


def build_seed_snapshot() -> dict:
    symbols = [
        {
            "symbol": "EURUSD",
            "state": "context_found",
            "price": 1.08462,
            "bias": "bullish",
            "tf": "H4",
            "phase": "LTF_SWEEP",
            "reason": "waiting: LTF sweep near H4 bullish FVG",
            "score": 1.7,
            "grade": "C",
            "last_update": "2026-03-21T08:52:11",
            "cooldown_remaining": 0,
            "detail": {
                "current_state": "context_found",
                "htf_bias": "bullish",
                "market_structure_bias": "bullish",
                "liquidity_interaction_state": "-",
                "reaction_strength": "light",
                "phase": "LTF Sweep",
                "htf_context": "H4 bullish FVG",
                "htf_zone_type": "H4 FVG",
                "htf_zone_source": "H4 FVG candle @ 2026-03-20 04:00 UTC | idx 118 | O 1.0824 H 1.0852 L 1.0819 C 1.0846",
                "htf_context_reason": "H4 bullish context active (zone=0.88, reaction=0.74, trend=Bullish)",
                "last_detected_sweep": "-",
                "last_detected_mss": "waiting for MSS after sweep",
                "last_detected_ifvg": "-",
                "rejection_reason": "-",
                "last_alert_time": "-",
                "last_alert_details": "-",
                "cooldown_info": "-",
                "active_watch_id": None,
                "active_watch_info": "-",
                "zone": "H4 bullish FVG | 1.0838-1.0851",
                "zone_top_bottom": "-",
                "score": "C (1.7)",
                "timeline": "08:52 HTF context detected: H4 bullish FVG",
            },
        },
        {
            "symbol": "GBPUSD",
            "state": "waiting_mss",
            "price": 1.27457,
            "bias": "bullish",
            "tf": "M5",
            "phase": "WAITING_MSS",
            "reason": "waiting: MSS after sweep on M5",
            "score": 5.9,
            "grade": "C",
            "last_update": "2026-03-21T08:57:12",
            "cooldown_remaining": 0,
            "detail": {
                "current_state": "waiting_mss",
                "htf_bias": "bullish",
                "market_structure_bias": "bullish",
                "liquidity_interaction_state": "-",
                "reaction_strength": "moderate",
                "phase": "Waiting MSS",
                "htf_context": "H4 bullish FVG",
                "htf_zone_type": "H4 FVG",
                "htf_zone_source": "H4 FVG candle @ 2026-03-20 04:00 UTC | idx 118 | O 1.2721 H 1.2755 L 1.2718 C 1.2749",
                "htf_context_reason": "H4 bullish context active (zone=0.91, reaction=0.78, trend=Bullish)",
                "last_detected_sweep": "M5 sweep at 1.27418 (PDL)",
                "last_detected_mss": "waiting for MSS after sweep",
                "last_detected_ifvg": "iFVG 1.27420-1.27480",
                "rejection_reason": "-",
                "last_alert_time": "-",
                "last_alert_details": "-",
                "cooldown_info": "-",
                "active_watch_id": "GBPUSD|Long|M5|H4 bullish FVG|12|1.2742|1.2748",
                "active_watch_info": "M5 LONG | waiting for MSS",
                "zone": "H4 bullish FVG | 1.2734-1.2751",
                "zone_top_bottom": "1.27420-1.27480",
                "score": "C (5.9)",
                "timeline": "08:57 HTF context detected: H4 bullish FVG\n08:57 M5 sweep detected\n08:57 M5 strict iFVG detected",
            },
        },
        {
            "symbol": "USDCHF",
            "state": "rejected",
            "price": 0.90231,
            "bias": "bearish",
            "tf": "M15",
            "phase": "IFVG_VALIDATION",
            "reason": "rejected: no strict iFVG",
            "score": 3.2,
            "grade": "C",
            "last_update": "2026-03-21T08:58:33",
            "cooldown_remaining": 0,
            "detail": {
                "current_state": "rejected",
                "htf_bias": "bearish",
                "market_structure_bias": "bearish",
                "liquidity_interaction_state": "-",
                "reaction_strength": "light",
                "phase": "iFVG Validation",
                "htf_context": "H1 bearish OB",
                "htf_zone_type": "H1 OB",
                "htf_zone_source": "H1 OB candle @ 2026-03-21 06:00 UTC | idx 141 | O 0.9022 H 0.9029 L 0.9018 C 0.9027",
                "htf_context_reason": "H1 bearish context active (zone=0.72, reaction=0.61, trend=Bearish)",
                "last_detected_sweep": "M15 sweep at 0.90255 (PWH)",
                "last_detected_mss": "waiting for MSS after sweep",
                "last_detected_ifvg": "-",
                "rejection_reason": "rejected: no strict iFVG",
                "last_alert_time": "-",
                "last_alert_details": "-",
                "cooldown_info": "-",
                "active_watch_id": None,
                "active_watch_info": "-",
                "zone": "H1 bearish OB | 0.9021-0.9029",
                "zone_top_bottom": "-",
                "score": "C (3.2)",
                "timeline": "08:58 HTF context detected: H1 bearish OB\n08:58 rejected: no strict iFVG",
            },
        },
    ]

    watches = [
        {
            "symbol": "GBPUSD",
            "direction": "LONG",
            "htf_context": "H4 bullish FVG",
            "ltf_tf": "M5",
            "state": "waiting_mss",
            "waiting_for": "MSS",
            "ltf_sweep_status": "sweep detected",
            "score": 5.9,
            "grade": "C",
            "zone_top": 1.2748,
            "zone_bottom": 1.2742,
            "armed_at": "2026-03-21T08:57:12",
            "bias": "Long",
            "watch_key": "GBPUSD|Long|M5|H4 bullish FVG|12|1.2742|1.2748",
            "status_reason": "armed: H4 bullish FVG + LTF sweep",
        }
    ]

    alerts = [
        {
            "time": "2026-03-21T08:41:15",
            "symbol": "XAUUSD",
            "tf": "M5",
            "direction": "LONG",
            "alert_type": "confirmed",
            "reason": "confirmed: MSS + strict iFVG",
            "entry": 2184.2,
            "sl": 2181.7,
            "status": "sent",
            "stage": "confirmed_signal",
            "event_key": "signal:XAUUSD|Long|M5|H4 bullish FVG|2184.2|2181.7",
            "channel": "telegram",
        },
        {
            "time": "2026-03-21T08:57:15",
            "symbol": "GBPUSD",
            "tf": "M5",
            "direction": "LONG",
            "alert_type": "armed",
            "reason": "armed: H4 bullish FVG + LTF sweep",
            "entry": 1.2742,
            "sl": 1.2736,
            "status": "sent",
            "stage": "watch_armed",
            "event_key": "watch:GBPUSD|Long|M5|H4 bullish FVG|12|1.2742|1.2748",
            "channel": "telegram",
        },
    ]

    logs = [
        {
            "timestamp": "2026-03-21T08:40:00",
            "label": "2026-03-21 08:40:00",
            "level": "INFO",
            "symbol": "-",
            "timeframe": "-",
            "phase": "connection",
            "reason": "",
            "message": "Connected to MT5",
        },
        {
            "timestamp": "2026-03-21T08:57:12",
            "label": "2026-03-21 08:57:12",
            "level": "WATCH",
            "symbol": "GBPUSD",
            "timeframe": "M5",
            "phase": "watch",
            "reason": "strict iFVG",
            "message": "watch armed after sweep",
        },
        {
            "timestamp": "2026-03-21T08:58:33",
            "label": "2026-03-21 08:58:33",
            "level": "WARN",
            "symbol": "USDCHF",
            "timeframe": "M15",
            "phase": "watch",
            "reason": "rejected: no strict iFVG",
            "message": "setup rejected",
        },
    ]

    return {
        "app": {
            "name": "OpenClaw Scanner",
            "version": "2.0.0",
            "strategy_version": "1.0.0",
        },
        "strategy": {
            "ob_fvg_mode": "medium",
        },
        "scanner": {
            "running": True,
            "status": "running",
            "interval_sec": 60,
            "started_at": 0,
            "last_cycle": None,
            "last_error": None,
        },
        "connections": {
            "mt5": {"connected": True, "terminal_name": "MetaTrader 5", "last_error": None},
            "telegram": {"configured": True, "enabled": True, "missing_fields": []},
        },
        "metrics": {
            "active_watches": 1,
            "confirmed_signals_today": 1,
            "total_symbols": 3,
            "scanned_symbols": 3,
        },
        "symbols": deepcopy(symbols),
        "watches": deepcopy(watches),
        "alerts": deepcopy(alerts),
        "logs": deepcopy(logs),
        "rejections": [],
    }
