HTF_ORDER_BLOCK_MIN_BARS = 12
HTF_ORDER_BLOCK_SCAN_START = 5
HTF_ORDER_BLOCK_CONFIRM_BARS = 3
HTF_ORDER_BLOCK_MAX_LOOKAHEAD = 6
HTF_ORDER_BLOCK_QUALITY_BASE = 0.2
HTF_ORDER_BLOCK_QUALITY_SCALE = 0.18
HTF_ORDER_BLOCK_TIMEFRAME_BONUS = {"H1": 0.05, "H4": 0.12}
HTF_ORDER_BLOCK_FVG_BONUS = 0.14
HTF_ORDER_BLOCK_SWEEP_BONUS = 0.08
HTF_ORDER_BLOCK_TREND_ALIGNMENT_BONUS = 0.06
HTF_ORDER_BLOCK_BOS_BONUS = 0.1
HTF_ORDER_BLOCK_DISPLACEMENT_BONUS = {"medium": 0.08, "strong": 0.16}
HTF_ORDER_BLOCK_MAX_ZONES = 6
HTF_ORDER_BLOCK_MAX_OVERLAP_BARS = 1
HTF_ORDER_BLOCK_OVERLAP_TOLERANCE_POINTS = 2
HTF_OB_USE_STRICT_BODY_ENGULF = True
HTF_OB_MIN_BODY_RATIO = 0.5
HTF_OB_MIN_DISPLACEMENT_RATIO = 0.75
HTF_OB_REQUIRE_LIQUIDITY_SWEEP = False
HTF_OB_FVG_MODE = "medium"
HTF_OB_FVG_PENALTY = 0.2
HTF_OB_INVALIDATION_USE_CLOSE = True
HTF_OB_INVALIDATION_BUFFER = 0.0

HTF_SWING_STRENGTH = 2
HTF_SWING_MIN_RANGE_RATIO = 0.9
HTF_SWING_MIN_SEPARATION = 2

HTF_BOS_CLOSE_BUFFER_POINTS = 2
HTF_BOS_WICK_BUFFER_POINTS = 1

HTF_DISPLACEMENT_MIN_BARS = 2
HTF_DISPLACEMENT_MIN_MOVE_MEDIUM = 1.0
HTF_DISPLACEMENT_MIN_MOVE_STRONG = 1.5
HTF_DISPLACEMENT_MIN_BODY_MEDIUM = 0.55
HTF_DISPLACEMENT_MIN_BODY_STRONG = 0.65
HTF_DISPLACEMENT_MIN_EFFICIENCY_MEDIUM = 0.45
HTF_DISPLACEMENT_MIN_EFFICIENCY_STRONG = 0.58
HTF_DISPLACEMENT_MIN_DIRECTIONAL_RATIO = 0.67
HTF_DISPLACEMENT_MAX_OPPOSITE_BARS = 1
HTF_DISPLACEMENT_MAX_WEAK_BODY_BARS = 1

HTF_FVG_MIN_BARS = 6
HTF_FVG_LOOKBACK = 2
HTF_FVG_MIN_GAP_RATIO = 0.1
HTF_FVG_MIN_VISIBLE_RANGE_RATIO = 0.16
HTF_FVG_MIN_WIDTH_TO_MOVE_RATIO = 0.12
HTF_FVG_QUALITY_BASE = 0.18
HTF_FVG_QUALITY_DIVISOR = 0.65
HTF_FVG_QUALITY_SCALE = 0.16
HTF_FVG_TIMEFRAME_BONUS = {"H1": 0.08, "H4": 0.16}
HTF_FVG_MIN_POINTS = 6
HTF_FVG_MAX_ZONES = 8
HTF_FVG_DISPLACEMENT_BODY_THRESHOLD = 0.6
HTF_FVG_DISPLACEMENT_BONUS = {"weak": -0.18, "medium": 0.12, "strong": 0.2}
HTF_FVG_BOS_BONUS = 0.12
HTF_FVG_SWEEP_BONUS = 0.08
HTF_FVG_TREND_ALIGNMENT_BONUS = 0.06
HTF_FVG_CONTEXT_MISSING_PENALTY = 0.12
HTF_FVG_RANGE_PENALTY = 0.12
HTF_FVG_LOCATION_BONUS = {"discount": 0.06, "premium": 0.06, "equilibrium": -0.06, "unknown": 0.0}
HTF_FVG_FOLLOW_THROUGH_BARS = 3
HTF_FVG_MIN_FOLLOW_THROUGH_RANGE_RATIO = 0.28
HTF_FVG_MAX_IMMEDIATE_FILL_RATIO = 0.7
HTF_FVG_FOLLOW_THROUGH_BONUS = {"weak": -0.12, "moderate": 0.04, "strong": 0.08}
HTF_FVG_PARTIAL_MITIGATION_RATIO = 0.25
HTF_FVG_DEEP_MITIGATION_RATIO = 0.7
HTF_FVG_FULL_MITIGATION_RATIO = 0.95
HTF_FVG_MITIGATION_PENALTY = {
    "untouched": 0.0,
    "partially_mitigated": 0.02,
    "deep_mitigated": 0.12,
    "filled": 0.24,
    "invalidated": 0.5,
}
HTF_FVG_CLASS_BONUS = {
    "impulse_fvg": 0.08,
    "trend_fvg": 0.05,
    "sweep_fvg": 0.07,
    "internal_fvg": -0.08,
    "weak_fvg": -0.16,
}
HTF_FVG_KEEP_MIN_QUALITY = 0.58
HTF_FVG_TRADABLE_MIN_QUALITY = 0.82
HTF_FVG_EXCEPTIONAL_MIN_QUALITY = 0.92
HTF_FVG_INVALIDATION_USE_CLOSE = True
HTF_FVG_INVALIDATION_BUFFER = 0.0

HTF_REFERENCE_BAND_H1_RATIO = 0.04
HTF_REFERENCE_BAND_H4_RATIO = 0.025
HTF_REFERENCE_BAND_MIN_POINTS = 12
HTF_PREVIOUS_DAY_QUALITY = 0.6
HTF_PREVIOUS_WEEK_QUALITY = 0.7
HTF_PREVIOUS_WEEK_BAND_MULTIPLIER = 1.4
HTF_LIQUIDITY_RECENT_BARS = {"D1": 12, "W1": 18}
HTF_LIQUIDITY_CONFIRMATION_BARS = 4
HTF_LIQUIDITY_NEUTRAL_SCORE_PENALTY = 0.24
HTF_LIQUIDITY_DIRECTIONAL_SCORE_PENALTY = 0.12

HTF_EVALUATION_RECENT_BARS = {"H1": 6, "H4": 3}
HTF_TOLERANCE_ZONE_WIDTH_RATIO = 0.6
HTF_TOLERANCE_AVG_H1_RATIO = 0.22
HTF_TOLERANCE_MIN_POINTS = 18
HTF_SWEEP_BUFFER_POINTS = 3
HTF_REACTION_STRONG = 1.0
HTF_REACTION_RESPECTED = 0.86
HTF_REACTION_NEAR_WITH_BODY = 0.76
HTF_REACTION_NEAR = 0.68
HTF_DISTANCE_BODY_THRESHOLD = 0.82
HTF_DISTANCE_NEAR_THRESHOLD = 0.75
HTF_CLEAR_REACTION_THRESHOLD = 0.86
HTF_CLEAR_DISTANCE_THRESHOLD = 0.92
HTF_CLEAR_ZONE_QUALITY_THRESHOLD = 0.82
HTF_COMPOSITE_DISTANCE_WEIGHT = 0.35
